server:
  port: 9088
myrpc:
  providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zkServers: localhost:2181
  zkNamespace: myrpc
app:
  id: app1
  namespace: public
  env: dev
  retry:
    max: 2
  timeout:
    default: 2000
    connect: 3000
    read: 3000
    write: 3000
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.flhai: DEBUG