server:
  port: 9088
myrpc:
  providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zkServers: localhost:2181
  zkNamespace: myrpc
app:
  id: app1
  namespace: public
  env: dev
  retry:
    max: 2
  timeout:
    default: 1000
    connect: 3000
    read: 3000
    write: 3000
  greyRate: 10 # 10%
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.flhai: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"