### get user info
POST http://localhost:8080
Content-Type: application/json

{
  "service": "com.flhai.myrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "params": [1001]
}

### get order info
POST http://localhost:8080
Content-Type: application/json

{
  "service": "com.flhai.myrpc.demo.api.OrderService",
  "method": "findOrderById",
  "params": [200]
}
### get order info
POST http://localhost:8080
Content-Type: application/json

{
  "service": "com.flhai.myrpc.demo.api.OrderService",
  "method": "findOrderById",
  "params": [404]
}

### get hashcode
POST http://localhost:8080
Content-Type: application/json

{
  "service": "com.flhai.myrpc.demo.api.OrderService",
  "method": "hashCode"
}


### get user info
GET http://localhost:8088/?id=101
