server:
  port: 8080
app:
  id: app1
  namespace: public
  env: dev
myrpc:
  zkServers: localhost:2181
  zkNamespace: myrpc
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.flhai: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"