server:
  port: 8080
myrpc:
  zk:
    servers: localhost:2181
    namespace: myrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      grey: false
      dc: dc0
      unit: unit0
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.flhai: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"